[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "ng build --configuration=staging"
  publish = "dist/angular-starter"

[context.production]
  command = "ng build --configuration=production"

[context.deploy-preview]
  command = "ng build --configuration=staging"