[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build:staging"
  publish = "dist/angular-starter"

[context.production]
  command = "npm run build"

[context.deploy-preview]
  command = "npm run build:staging"